-- 종목 정리 — 한국 유튜브 관심도 측정 결과 반영 (2026-09 조사)
--
-- 219 → 199 종목.
-- 1) 표준명도 별칭도 검색 결과가 0인 20종목 삭제.
--    지우는 대신 그 이름을 살아남는 종목의 별칭에 넣어, 검색은 계속 되게 했다
--    (예: '로프 푸시다운' 으로 검색하면 '케이블 푸시다운' 이 나온다).
-- 2) 표준명이 실제로 안 쓰이는 2종목 개명.
--    리어 델트 플라이 → 리버스 펙덱 (381,309 vs 0)
--    커시 런지       → 크로스 런지 (16,376 vs 0)
-- 3) 중량 계열에 '○○ 무게' / '○○ 중량' 별칭 추가.
--    사용자가 '딥스 무게' 를 못 찾아 커스텀 종목을 만든 실사용 기록이 근거다.
--
-- 삭제는 기록이 걸린 종목을 건너뛴다. 쓰인 종목이 사라지면 기록이 깨지기 때문이다.

-- ── 1. 개명 먼저. 아래 upsert 가 같은 행을 찾아야 한다 ──
update exercises set name = '리버스 펙덱' where owner_id is null and name = '리어 델트 플라이';
update exercises set name = '크로스 런지'  where owner_id is null and name = '커시 런지';

-- ── 2. 공용 종목 199개 upsert (별칭 흡수분 포함) ──
insert into exercises
  (name, chosung, aliases, alias_chosung, muscle_group, sub_region, equipment, tracking_type, asset_slug, owner_id)
values
  ('벤치프레스', 'ㅂㅊㅍㄹㅅ', array['벤프','바벨 벤치프레스','플랫 벤치프레스','벤치','bench press']::text[], array['ㅂㅍ','ㅂㅂㅂㅊㅍㄹㅅ','ㅍㄹㅂㅊㅍㄹㅅ','ㅂㅊ']::text[], 'chest', 'general', 'barbell', 'weight_reps', 'bench-press', null),
  ('인클라인 벤치프레스', 'ㅇㅋㄹㅇㅂㅊㅍㄹㅅ', array['인벤','인클라인 벤치','인클라인 프레스','incline bench press']::text[], array['ㅇㅂ','ㅇㅋㄹㅇㅂㅊ','ㅇㅋㄹㅇㅍㄹㅅ']::text[], 'chest', 'upper_chest', 'barbell', 'weight_reps', 'incline-bench-press', null),
  ('디클라인 벤치프레스', 'ㄷㅋㄹㅇㅂㅊㅍㄹㅅ', array['디벤','디클라인 벤치','decline bench press']::text[], array['ㄷㅂ','ㄷㅋㄹㅇㅂㅊ']::text[], 'chest', 'general', 'barbell', 'weight_reps', 'decline-bench-press', null),
  ('덤벨 벤치프레스', 'ㄷㅂㅂㅊㅍㄹㅅ', array['덤벤','덤벨 프레스','플랫 덤벨 프레스','dumbbell bench press']::text[], array['ㄷㅂ','ㄷㅂㅍㄹㅅ','ㅍㄹㄷㅂㅍㄹㅅ']::text[], 'chest', 'general', 'dumbbell', 'weight_reps', 'dumbbell-bench-press', null),
  ('인클라인 덤벨 프레스', 'ㅇㅋㄹㅇㄷㅂㅍㄹㅅ', array['인덤프','인클라인 덤벨 벤치프레스','incline dumbbell press']::text[], array['ㅇㄷㅍ','ㅇㅋㄹㅇㄷㅂㅂㅊㅍㄹㅅ']::text[], 'chest', 'upper_chest', 'dumbbell', 'weight_reps', 'incline-dumbbell-press', null),
  ('디클라인 덤벨 프레스', 'ㄷㅋㄹㅇㄷㅂㅍㄹㅅ', array['디클라인 덤벨 벤치프레스','decline dumbbell press']::text[], array['ㄷㅋㄹㅇㄷㅂㅂㅊㅍㄹㅅ']::text[], 'chest', 'general', 'dumbbell', 'weight_reps', 'decline-dumbbell-press', null),
  ('덤벨 플라이', 'ㄷㅂㅍㄹㅇ', array['플라이','덤벨 플라이스','dumbbell fly','dumbbell flye']::text[], array['ㅍㄹㅇ','ㄷㅂㅍㄹㅇㅅ']::text[], 'chest', 'general', 'dumbbell', 'weight_reps', 'dumbbell-fly', null),
  ('인클라인 덤벨 플라이', 'ㅇㅋㄹㅇㄷㅂㅍㄹㅇ', array['인클라인 플라이','incline dumbbell fly']::text[], array['ㅇㅋㄹㅇㅍㄹㅇ']::text[], 'chest', 'upper_chest', 'dumbbell', 'weight_reps', null, null),
  ('케이블 크로스오버', 'ㅋㅇㅂㅋㄹㅅㅇㅂ', array['크로스오버','케이블 플라이','스탠딩 케이블 플라이','cable crossover','cable fly']::text[], array['ㅋㄹㅅㅇㅂ','ㅋㅇㅂㅍㄹㅇ','ㅅㅌㄷㅋㅇㅂㅍㄹㅇ']::text[], 'chest', 'general', 'cable', 'weight_reps', 'cable-fly', null),
  ('인클라인 케이블 플라이', 'ㅇㅋㄹㅇㅋㅇㅂㅍㄹㅇ', array['로우 케이블 플라이','로우 풀리 케이블 플라이','incline cable fly']::text[], array['ㄹㅇㅋㅇㅂㅍㄹㅇ','ㄹㅇㅍㄹㅋㅇㅂㅍㄹㅇ']::text[], 'chest', 'upper_chest', 'cable', 'weight_reps', 'incline-cable-fly', null),
  ('체스트 프레스', 'ㅊㅅㅌㅍㄹㅅ', array['체프','머신 체스트 프레스','체스트 프레스 머신','chest press']::text[], array['ㅊㅍ','ㅁㅅㅊㅅㅌㅍㄹㅅ','ㅊㅅㅌㅍㄹㅅㅁㅅ']::text[], 'chest', 'general', 'machine', 'weight_reps', 'machine-chest-press', null),
  ('펙덱 플라이', 'ㅍㄷㅍㄹㅇ', array['버터플라이','펙덱','머신 플라이','펙덱 플라이 머신','pec deck']::text[], array['ㅂㅌㅍㄹㅇ','ㅍㄷ','ㅁㅅㅍㄹㅇ','ㅍㄷㅍㄹㅇㅁㅅ']::text[], 'chest', 'general', 'machine', 'weight_reps', 'pec-deck', null),
  ('스미스 머신 벤치프레스', 'ㅅㅁㅅㅁㅅㅂㅊㅍㄹㅅ', array['스미스 벤치','smith machine bench press']::text[], array['ㅅㅁㅅㅂㅊ']::text[], 'chest', 'general', 'machine', 'weight_reps', 'smith-machine-bench-press', null),
  ('스미스 머신 인클라인 벤치프레스', 'ㅅㅁㅅㅁㅅㅇㅋㄹㅇㅂㅊㅍㄹㅅ', array['스미스 인클라인 벤치']::text[], array['ㅅㅁㅅㅇㅋㄹㅇㅂㅊ']::text[], 'chest', 'upper_chest', 'machine', 'weight_reps', null, null),
  ('딥스', 'ㄷㅅ', array['체스트 딥스','평행봉','dips','chest dip']::text[], array['ㅊㅅㅌㄷㅅ','ㅍㅎㅂ']::text[], 'chest', 'general', 'bodyweight', 'bodyweight_reps', 'chest-dip', null),
  ('중량 딥스', 'ㅈㄹㄷㅅ', array['웨이티드 딥스','가중 딥스','딥벨트 딥스','weighted dip','딥스 무게','딥스 중량']::text[], array['ㅇㅇㅌㄷㄷㅅ','ㄱㅈㄷㅅ','ㄷㅂㅌㄷㅅ','ㄷㅅㅁㄱ','ㄷㅅㅈㄹ']::text[], 'chest', 'general', 'bodyweight', 'weight_reps', 'weighted-dip', null),
  ('푸시업', 'ㅍㅅㅇ', array['클랩 푸시업','팔굽혀펴기','푸쉬업','push up']::text[], array['ㅋㄹㅍㅅㅇ','ㅍㄱㅎㅍㄱ','ㅍㅅㅇ']::text[], 'chest', 'general', 'bodyweight', 'bodyweight_reps', 'push-up', null),
  ('중량 푸시업', 'ㅈㄹㅍㅅㅇ', array['중량 푸쉬업','웨이티드 푸시업','weighted push up','푸시업 무게','푸시업 중량']::text[], array['ㅈㄹㅍㅅㅇ','ㅇㅇㅌㄷㅍㅅㅇ','ㅍㅅㅇㅁㄱ','ㅍㅅㅇㅈㄹ']::text[], 'chest', 'general', 'bodyweight', 'weight_reps', 'weighted-push-up', null),
  ('와이드 푸시업', 'ㅇㅇㄷㅍㅅㅇ', array['와이드 푸쉬업','와이드그립 푸시업','wide push up']::text[], array['ㅇㅇㄷㅍㅅㅇ','ㅇㅇㄷㄱㄹㅍㅅㅇ']::text[], 'chest', 'general', 'bodyweight', 'bodyweight_reps', 'wide-push-up', null),
  ('인클라인 푸시업', 'ㅇㅋㄹㅇㅍㅅㅇ', array['인클라인 푸쉬업','상체 올린 푸시업','incline push up']::text[], array['ㅇㅋㄹㅇㅍㅅㅇ','ㅅㅊㅇㄹㅍㅅㅇ']::text[], 'chest', 'general', 'bodyweight', 'bodyweight_reps', 'incline-push-up', null),
  ('디클라인 푸시업', 'ㄷㅋㄹㅇㅍㅅㅇ', array['디클라인 푸쉬업','발 올린 푸시업','decline push up']::text[], array['ㄷㅋㄹㅇㅍㅅㅇ','ㅂㅇㄹㅍㅅㅇ']::text[], 'chest', 'general', 'bodyweight', 'bodyweight_reps', 'decline-push-up', null),
  ('무릎 푸시업', 'ㅁㄹㅍㅅㅇ', array['니 푸쉬업','니 푸시업','무릎대고 푸시업','knee push up']::text[], array['ㄴㅍㅅㅇ','ㄴㅍㅅㅇ','ㅁㄹㄷㄱㅍㅅㅇ']::text[], 'chest', 'general', 'bodyweight', 'bodyweight_reps', 'knee-push-up', null),
  ('아처 푸시업', 'ㅇㅊㅍㅅㅇ', array['아처 푸쉬업','archer push up']::text[], array['ㅇㅊㅍㅅㅇ']::text[], 'chest', 'general', 'bodyweight', 'bodyweight_reps', 'archer-push-up', null),
  ('힌두 푸시업', 'ㅎㄷㅍㅅㅇ', array['힌두 푸쉬업','hindu push up']::text[], array['ㅎㄷㅍㅅㅇ']::text[], 'chest', 'general', 'bodyweight', 'bodyweight_reps', 'hindu-push-up', null),
  ('인클라인 체스트 프레스 머신', 'ㅇㅋㄹㅇㅊㅅㅌㅍㄹㅅㅁㅅ', array['인클라인 체프','인클라인 머신 프레스','인클라인 벤치프레스 머신']::text[], array['ㅇㅋㄹㅇㅊㅍ','ㅇㅋㄹㅇㅁㅅㅍㄹㅅ','ㅇㅋㄹㅇㅂㅊㅍㄹㅅㅁㅅ']::text[], 'chest', 'upper_chest', 'machine', 'weight_reps', null, null),
  ('데드리프트', 'ㄷㄷㄹㅍㅌ', array['데드','컨벤셔널 데드리프트','deadlift']::text[], array['ㄷㄷ','ㅋㅂㅅㄴㄷㄷㄹㅍㅌ']::text[], 'back', 'erectors', 'barbell', 'weight_reps', 'deadlift', null),
  ('스모 데드리프트', 'ㅅㅁㄷㄷㄹㅍㅌ', array['스모 데드','sumo deadlift']::text[], array['ㅅㅁㄷㄷ']::text[], 'back', 'erectors', 'barbell', 'weight_reps', 'sumo-deadlift', null),
  ('트랩바 데드리프트', 'ㅌㄹㅂㄷㄷㄹㅍㅌ', array['트랩바 데드','헥스바 데드리프트','trap bar deadlift']::text[], array['ㅌㄹㅂㄷㄷ','ㅎㅅㅂㄷㄷㄹㅍㅌ']::text[], 'back', 'erectors', 'barbell', 'weight_reps', 'trap-bar-deadlift', null),
  ('랙풀', 'ㄹㅍ', array['rack pull']::text[], '{}'::text[], 'back', 'erectors', 'barbell', 'weight_reps', 'rack-pull', null),
  ('바벨 로우', 'ㅂㅂㄹㅇ', array['메도우즈 로우','벤트오버 로우','바벨 벤트오버 로우','barbell row','bent over row']::text[], array['ㅁㄷㅇㅈㄹㅇ','ㅂㅌㅇㅂㄹㅇ','ㅂㅂㅂㅌㅇㅂㄹㅇ']::text[], 'back', 'general', 'barbell', 'weight_reps', 'barbell-row', null),
  ('펜들레이 로우', 'ㅍㄷㄹㅇㄹㅇ', array['펜들레이','pendlay row']::text[], array['ㅍㄷㄹㅇ']::text[], 'back', 'general', 'barbell', 'weight_reps', 'pendlay-row', null),
  ('언더그립 바벨 로우', 'ㅇㄷㄱㄹㅂㅂㄹㅇ', array['언더핸드 바벨 로우','리버스그립 바벨 로우']::text[], array['ㅇㄷㅎㄷㅂㅂㄹㅇ','ㄹㅂㅅㄱㄹㅂㅂㄹㅇ']::text[], 'back', 'general', 'barbell', 'weight_reps', null, null),
  ('바벨 풀오버', 'ㅂㅂㅍㅇㅂ', array['풀오버','barbell pullover']::text[], array['ㅍㅇㅂ']::text[], 'back', 'lats', 'barbell', 'weight_reps', null, null),
  ('덤벨 풀오버', 'ㄷㅂㅍㅇㅂ', array['풀오버','dumbbell pullover']::text[], array['ㅍㅇㅂ']::text[], 'back', 'lats', 'dumbbell', 'weight_reps', null, null),
  ('원암 덤벨 로우', 'ㅇㅇㄷㅂㄹㅇ', array['덤벨 로우','원암 로우','one arm dumbbell row']::text[], array['ㄷㅂㄹㅇ','ㅇㅇㄹㅇ']::text[], 'back', 'general', 'dumbbell', 'weight_reps', 'one-arm-dumbbell-row', null),
  ('덤벨 벤트오버 로우', 'ㄷㅂㅂㅌㅇㅂㄹㅇ', array['양손 덤벨 로우','덤벨 로우','dumbbell bent over row']::text[], array['ㅇㅅㄷㅂㄹㅇ','ㄷㅂㄹㅇ']::text[], 'back', 'general', 'dumbbell', 'weight_reps', 'dumbbell-bent-over-row', null),
  ('덤벨 인클라인 로우', 'ㄷㅂㅇㅋㄹㅇㄹㅇ', array['체스트 서포티드 덤벨 로우','인클라인 벤치 덤벨 로우']::text[], array['ㅊㅅㅌㅅㅍㅌㄷㄷㅂㄹㅇ','ㅇㅋㄹㅇㅂㅊㄷㅂㄹㅇ']::text[], 'back', 'general', 'dumbbell', 'weight_reps', null, null),
  ('랫풀다운', 'ㄹㅍㄷㅇ', array['언더그립 랫풀다운','클로즈그립 랫풀다운','랫풀','렛풀다운','와이드그립 랫풀다운','lat pulldown']::text[], array['ㅇㄷㄱㄹㄹㅍㄷㅇ','ㅋㄹㅈㄱㄹㄹㅍㄷㅇ','ㄹㅍ','ㄹㅍㄷㅇ','ㅇㅇㄷㄱㄹㄹㅍㄷㅇ']::text[], 'back', 'lats', 'cable', 'weight_reps', 'lat-pulldown', null),
  ('원암 케이블 랫풀다운', 'ㅇㅇㅋㅇㅂㄹㅍㄷㅇ', array['원암 풀다운','한팔 랫풀다운']::text[], array['ㅇㅇㅍㄷㅇ','ㅎㅍㄹㅍㄷㅇ']::text[], 'back', 'lats', 'cable', 'weight_reps', null, null),
  ('시티드 로우', 'ㅅㅌㄷㄹㅇ', array['케이블 로우','시티드 케이블 로우','로우','seated row','seated cable row']::text[], array['ㅋㅇㅂㄹㅇ','ㅅㅌㄷㅋㅇㅂㄹㅇ','ㄹㅇ']::text[], 'back', 'general', 'cable', 'weight_reps', 'seated-row', null),
  ('원암 케이블 로우', 'ㅇㅇㅋㅇㅂㄹㅇ', array['원암 시티드 케이블 로우','한팔 케이블 로우','single arm cable row']::text[], array['ㅇㅇㅅㅌㄷㅋㅇㅂㄹㅇ','ㅎㅍㅋㅇㅂㄹㅇ']::text[], 'back', 'general', 'cable', 'weight_reps', 'single-arm-cable-row', null),
  ('스트레이트 암 풀다운', 'ㅅㅌㄹㅇㅌㅇㅍㄷㅇ', array['암풀다운','케이블 암 풀다운','케이블 풀오버','straight arm pulldown']::text[], array['ㅇㅍㄷㅇ','ㅋㅇㅂㅇㅍㄷㅇ','ㅋㅇㅂㅍㅇㅂ']::text[], 'back', 'lats', 'cable', 'weight_reps', 'straight-arm-pulldown', null),
  ('티바 로우', 'ㅌㅂㄹㅇ', array['T바 로우','티바','티바 로우 머신','T-bar row']::text[], array['tㅂㄹㅇ','ㅌㅂ','ㅌㅂㄹㅇㅁㅅ']::text[], 'back', 'general', 'machine', 'weight_reps', 't-bar-row', null),
  ('체스트 서포티드 로우', 'ㅊㅅㅌㅅㅍㅌㄷㄹㅇ', array['체스트 서포티드 티바 로우','시티드 체스트 로우','chest supported row']::text[], array['ㅊㅅㅌㅅㅍㅌㄷㅌㅂㄹㅇ','ㅅㅌㄷㅊㅅㅌㄹㅇ']::text[], 'back', 'general', 'machine', 'weight_reps', 'chest-supported-row', null),
  ('머신 로우', 'ㅁㅅㄹㅇ', array['시티드 로우 머신','로우 로우 머신','미드 로우 머신','machine row']::text[], array['ㅅㅌㄷㄹㅇㅁㅅ','ㄹㅇㄹㅇㅁㅅ','ㅁㄷㄹㅇㅁㅅ']::text[], 'back', 'general', 'machine', 'weight_reps', 'machine-row', null),
  ('스미스 머신 로우', 'ㅅㅁㅅㅁㅅㄹㅇ', array['스미스 머신 바벨 로우','스미스 벤트오버 로우']::text[], array['ㅅㅁㅅㅁㅅㅂㅂㄹㅇ','ㅅㅁㅅㅂㅌㅇㅂㄹㅇ']::text[], 'back', 'general', 'machine', 'weight_reps', null, null),
  ('풀업', 'ㅍㅇ', array['턱걸이','광배 턱걸이','pull up']::text[], array['ㅌㄱㅇ','ㄱㅂㅌㄱㅇ']::text[], 'back', 'lats', 'bodyweight', 'bodyweight_reps', 'pull-up', null),
  ('중량 풀업', 'ㅈㄹㅍㅇ', array['웨이티드 풀업','가중 풀업','딥벨트 풀업','weighted pull up','풀업 무게','풀업 중량']::text[], array['ㅇㅇㅌㄷㅍㅇ','ㄱㅈㅍㅇ','ㄷㅂㅌㅍㅇ','ㅍㅇㅁㄱ','ㅍㅇㅈㄹ']::text[], 'back', 'lats', 'bodyweight', 'weight_reps', 'weighted-pull-up', null),
  ('친업', 'ㅊㅇ', array['언더그립 풀업','chin up']::text[], array['ㅇㄷㄱㄹㅍㅇ']::text[], 'back', 'lats', 'bodyweight', 'bodyweight_reps', 'chin-up', null),
  ('중량 친업', 'ㅈㄹㅊㅇ', array['웨이티드 친업','weighted chin up','친업 무게','친업 중량']::text[], array['ㅇㅇㅌㄷㅊㅇ','ㅊㅇㅁㄱ','ㅊㅇㅈㄹ']::text[], 'back', 'lats', 'bodyweight', 'weight_reps', 'weighted-chin-up', null),
  ('패러럴그립 풀업', 'ㅍㄹㄹㄱㄹㅍㅇ', array['뉴트럴그립 풀업','중립그립 풀업','neutral grip pull up']::text[], array['ㄴㅌㄹㄱㄹㅍㅇ','ㅈㄹㄱㄹㅍㅇ']::text[], 'back', 'lats', 'bodyweight', 'bodyweight_reps', 'neutral-grip-pull-up', null),
  ('어시스트 풀업 머신', 'ㅇㅅㅅㅌㅍㅇㅁㅅ', array['어시스트 풀업','보조 풀업','그래비트론','assisted pull up']::text[], array['ㅇㅅㅅㅌㅍㅇ','ㅂㅈㅍㅇ','ㄱㄹㅂㅌㄹ']::text[], 'back', 'lats', 'machine', 'assist_reps', 'assisted-pull-up', null),
  ('어시스트 친업 머신', 'ㅇㅅㅅㅌㅊㅇㅁㅅ', array['어시스트 친업','언더그립 어시스트 풀업','assisted chin up']::text[], array['ㅇㅅㅅㅌㅊㅇ','ㅇㄷㄱㄹㅇㅅㅅㅌㅍㅇ']::text[], 'back', 'lats', 'machine', 'assist_reps', 'assisted-chin-up', null),
  ('인버티드 로우', 'ㅇㅂㅌㄷㄹㅇ', array['호리즌탈 로우','수평 턱걸이','inverted row']::text[], array['ㅎㄹㅈㅌㄹㅇ','ㅅㅍㅌㄱㅇ']::text[], 'back', 'general', 'bodyweight', 'bodyweight_reps', 'inverted-row', null),
  ('바벨 슈러그', 'ㅂㅂㅅㄹㄱ', array['슈러그','승모근','barbell shrug']::text[], array['ㅅㄹㄱ','ㅅㅁㄱ']::text[], 'back', 'traps', 'barbell', 'weight_reps', 'shrug', null),
  ('덤벨 슈러그', 'ㄷㅂㅅㄹㄱ', array['슈러그','dumbbell shrug']::text[], array['ㅅㄹㄱ']::text[], 'back', 'traps', 'dumbbell', 'weight_reps', 'dumbbell-shrug', null),
  ('백 익스텐션', 'ㅂㅇㅅㅌㅅ', array['하이퍼익스텐션','백익스','로만체어','back extension']::text[], array['ㅎㅇㅍㅇㅅㅌㅅ','ㅂㅇㅅ','ㄹㅁㅊㅇ']::text[], 'back', 'erectors', 'bodyweight', 'bodyweight_reps', 'back-extension', null),
  ('백 익스텐션 머신', 'ㅂㅇㅅㅌㅅㅁㅅ', array['백익스 머신','시티드 백 익스텐션']::text[], array['ㅂㅇㅅㅁㅅ','ㅅㅌㄷㅂㅇㅅㅌㅅ']::text[], 'back', 'erectors', 'machine', 'weight_reps', null, null),
  ('와이드그립 풀업', 'ㅇㅇㄷㄱㄹㅍㅇ', array['와이드 풀업','넓게 잡는 턱걸이','wide grip pull up']::text[], array['ㅇㅇㄷㅍㅇ','ㄴㄱㅈㄴㅌㄱㅇ']::text[], 'back', 'lats', 'bodyweight', 'bodyweight_reps', null, null),
  ('케이블 슈러그', 'ㅋㅇㅂㅅㄹㄱ', array['케이블 승모','cable shrug']::text[], array['ㅋㅇㅂㅅㅁ']::text[], 'back', 'traps', 'cable', 'weight_reps', null, null),
  ('스미스 머신 슈러그', 'ㅅㅁㅅㅁㅅㅅㄹㄱ', array['스미스 슈러그']::text[], array['ㅅㅁㅅㅅㄹㄱ']::text[], 'back', 'traps', 'machine', 'weight_reps', null, null),
  ('풀오버 머신', 'ㅍㅇㅂㅁㅅ', array['머신 풀오버','랫 풀오버 머신']::text[], array['ㅁㅅㅍㅇㅂ','ㄹㅍㅇㅂㅁㅅ']::text[], 'back', 'lats', 'machine', 'weight_reps', null, null),
  ('하이 로우 머신', 'ㅎㅇㄹㅇㅁㅅ', array['하이로우','high row']::text[], array['ㅎㅇㄹㅇ']::text[], 'back', 'general', 'machine', 'weight_reps', null, null),
  ('오버헤드 프레스', 'ㅇㅂㅎㄷㅍㄹㅅ', array['밀리터리 프레스','밀프','OHP','바벨 숄더프레스','overhead press','military press']::text[], array['ㅁㄹㅌㄹㅍㄹㅅ','ㅁㅍ','ㅂㅂㅅㄷㅍㄹㅅ']::text[], 'shoulder', 'front_delt', 'barbell', 'weight_reps', 'overhead-press', null),
  ('푸시 프레스', 'ㅍㅅㅍㄹㅅ', array['푸쉬 프레스','push press']::text[], array['ㅍㅅㅍㄹㅅ']::text[], 'shoulder', 'front_delt', 'barbell', 'weight_reps', 'push-press', null),
  ('랜드마인 프레스', 'ㄹㄷㅁㅇㅍㄹㅅ', array['원암 랜드마인 프레스','landmine press']::text[], array['ㅇㅇㄹㄷㅁㅇㅍㄹㅅ']::text[], 'shoulder', 'front_delt', 'barbell', 'weight_reps', 'landmine-press', null),
  ('비하인드 넥 프레스', 'ㅂㅎㅇㄷㄴㅍㄹㅅ', array['비하인드 넥 숄더프레스','behind the neck press']::text[], array['ㅂㅎㅇㄷㄴㅅㄷㅍㄹㅅ']::text[], 'shoulder', 'front_delt', 'barbell', 'weight_reps', null, null),
  ('업라이트 로우', 'ㅇㄹㅇㅌㄹㅇ', array['업로우','바벨 업라이트 로우','upright row']::text[], array['ㅇㄹㅇ','ㅂㅂㅇㄹㅇㅌㄹㅇ']::text[], 'shoulder', 'side_delt', 'barbell', 'weight_reps', 'upright-row', null),
  ('바벨 프론트 레이즈', 'ㅂㅂㅍㄹㅌㄹㅇㅈ', array['이지바 프론트 레이즈','바벨 전면 레이즈']::text[], array['ㅇㅈㅂㅍㄹㅌㄹㅇㅈ','ㅂㅂㅈㅁㄹㅇㅈ']::text[], 'shoulder', 'front_delt', 'barbell', 'weight_reps', null, null),
  ('덤벨 숄더프레스', 'ㄷㅂㅅㄷㅍㄹㅅ', array['숄프','숄더프레스','시티드 덤벨 숄더 프레스','dumbbell shoulder press']::text[], array['ㅅㅍ','ㅅㄷㅍㄹㅅ','ㅅㅌㄷㄷㅂㅅㄷㅍㄹㅅ']::text[], 'shoulder', 'front_delt', 'dumbbell', 'weight_reps', 'seated-dumbbell-press', null),
  ('스탠딩 덤벨 프레스', 'ㅅㅌㄷㄷㅂㅍㄹㅅ', array['스탠딩 덤벨 숄더프레스','standing dumbbell press']::text[], array['ㅅㅌㄷㄷㅂㅅㄷㅍㄹㅅ']::text[], 'shoulder', 'front_delt', 'dumbbell', 'weight_reps', 'standing-dumbbell-press', null),
  ('아놀드 프레스', 'ㅇㄴㄷㅍㄹㅅ', array['아놀드 덤벨 프레스','arnold press']::text[], array['ㅇㄴㄷㄷㅂㅍㄹㅅ']::text[], 'shoulder', 'front_delt', 'dumbbell', 'weight_reps', 'arnold-press', null),
  ('사이드 레터럴 레이즈', 'ㅅㅇㄷㄹㅌㄹㄹㅇㅈ', array['사레레','레터럴 레이즈','래터럴 레이즈','덤벨 레터럴 레이즈','옆으로 들기','lateral raise']::text[], array['ㅅㄹㄹ','ㄹㅌㄹㄹㅇㅈ','ㄹㅌㄹㄹㅇㅈ','ㄷㅂㄹㅌㄹㄹㅇㅈ','ㅇㅇㄹㄷㄱ']::text[], 'shoulder', 'side_delt', 'dumbbell', 'weight_reps', 'lateral-raise', null),
  ('프론트 레이즈', 'ㅍㄹㅌㄹㅇㅈ', array['전면 레이즈','덤벨 프론트 레이즈','front raise']::text[], array['ㅈㅁㄹㅇㅈ','ㄷㅂㅍㄹㅌㄹㅇㅈ']::text[], 'shoulder', 'front_delt', 'dumbbell', 'weight_reps', 'front-raise', null),
  ('리어 델트 레이즈', 'ㄹㅇㄷㅌㄹㅇㅈ', array['리어 레터럴 레이즈','후면 레이즈','rear delt raise','rear delt fly']::text[], array['ㄹㅇㄹㅌㄹㄹㅇㅈ','ㅎㅁㄹㅇㅈ']::text[], 'shoulder', 'rear_delt', 'dumbbell', 'weight_reps', 'rear-delt-fly', null),
  ('벤트오버 리어 델트 레이즈', 'ㅂㅌㅇㅂㄹㅇㄷㅌㄹㅇㅈ', array['벤오레','벤트오버 레터럴 레이즈','벤트오버 덤벨 레터럴 레이즈','bent over rear delt raise']::text[], array['ㅂㅇㄹ','ㅂㅌㅇㅂㄹㅌㄹㄹㅇㅈ','ㅂㅌㅇㅂㄷㅂㄹㅌㄹㄹㅇㅈ']::text[], 'shoulder', 'rear_delt', 'dumbbell', 'weight_reps', 'bent-over-rear-delt-raise', null),
  ('머신 숄더프레스', 'ㅁㅅㅅㄷㅍㄹㅅ', array['숄더 프레스 머신','shoulder press machine']::text[], array['ㅅㄷㅍㄹㅅㅁㅅ']::text[], 'shoulder', 'front_delt', 'machine', 'weight_reps', 'machine-shoulder-press', null),
  ('스미스 머신 오버헤드 프레스', 'ㅅㅁㅅㅁㅅㅇㅂㅎㄷㅍㄹㅅ', array['스미스 숄더프레스']::text[], array['ㅅㅁㅅㅅㄷㅍㄹㅅ']::text[], 'shoulder', 'front_delt', 'machine', 'weight_reps', null, null),
  ('머신 레터럴 레이즈', 'ㅁㅅㄹㅌㄹㄹㅇㅈ', array['레터럴 레이즈 머신','machine lateral raise']::text[], array['ㄹㅌㄹㄹㅇㅈㅁㅅ']::text[], 'shoulder', 'side_delt', 'machine', 'weight_reps', 'machine-lateral-raise', null),
  ('리버스 펙덱', 'ㄹㅂㅅㅍㄷ', array['리어 델트 플라이','리어 델토이드 플라이 머신','머신 리어 델트','reverse pec deck']::text[], array['ㄹㅇㄷㅌㅍㄹㅇ','ㄹㅇㄷㅌㅇㄷㅍㄹㅇㅁㅅ','ㅁㅅㄹㅇㄷㅌ']::text[], 'shoulder', 'rear_delt', 'machine', 'weight_reps', 'reverse-pec-deck', null),
  ('케이블 레터럴 레이즈', 'ㅋㅇㅂㄹㅌㄹㄹㅇㅈ', array['원암 케이블 레터럴 레이즈','cable lateral raise']::text[], array['ㅇㅇㅋㅇㅂㄹㅌㄹㄹㅇㅈ']::text[], 'shoulder', 'side_delt', 'cable', 'weight_reps', 'cable-lateral-raise', null),
  ('케이블 프론트 레이즈', 'ㅋㅇㅂㅍㄹㅌㄹㅇㅈ', array['케이블 전면 레이즈','cable front raise']::text[], array['ㅋㅇㅂㅈㅁㄹㅇㅈ']::text[], 'shoulder', 'front_delt', 'cable', 'weight_reps', 'cable-front-raise', null),
  ('케이블 리어 델트 플라이', 'ㅋㅇㅂㄹㅇㄷㅌㅍㄹㅇ', array['케이블 리버스 플라이','cable rear delt fly']::text[], array['ㅋㅇㅂㄹㅂㅅㅍㄹㅇ']::text[], 'shoulder', 'rear_delt', 'cable', 'weight_reps', 'cable-rear-delt-fly', null),
  ('페이스풀', 'ㅍㅇㅅㅍ', array['face pull']::text[], '{}'::text[], 'shoulder', 'rear_delt', 'cable', 'weight_reps', 'face-pull', null),
  ('플레이트 프론트 레이즈', 'ㅍㄹㅇㅌㅍㄹㅌㄹㅇㅈ', array['원판 프론트 레이즈','plate front raise']::text[], array['ㅇㅍㅍㄹㅌㄹㅇㅈ']::text[], 'shoulder', 'front_delt', 'other', 'weight_reps', 'plate-front-raise', null),
  ('밴드 풀 어파트', 'ㅂㄷㅍㅇㅍㅌ', array['band pull apart']::text[], '{}'::text[], 'shoulder', 'rear_delt', 'band', 'bodyweight_reps', 'band-pull-apart', null),
  ('파이크 푸시업', 'ㅍㅇㅋㅍㅅㅇ', array['파이크 푸쉬업','pike push up']::text[], array['ㅍㅇㅋㅍㅅㅇ']::text[], 'shoulder', 'front_delt', 'bodyweight', 'bodyweight_reps', 'pike-push-up', null),
  ('핸드스탠드 푸시업', 'ㅎㄷㅅㅌㄷㅍㅅㅇ', array['물구나무 푸쉬업','핸드스탠드','handstand push up']::text[], array['ㅁㄱㄴㅁㅍㅅㅇ','ㅎㄷㅅㅌㄷ']::text[], 'shoulder', 'front_delt', 'bodyweight', 'bodyweight_reps', 'handstand-push-up', null),
  ('덤벨 업라이트 로우', 'ㄷㅂㅇㄹㅇㅌㄹㅇ', array['덤벨 업로우','dumbbell upright row']::text[], array['ㄷㅂㅇㄹㅇ']::text[], 'shoulder', 'side_delt', 'dumbbell', 'weight_reps', null, null),
  ('스쿼트', 'ㅅㅋㅌ', array['바벨 스쿼트','백스쿼트','하이바 스쿼트','squat','back squat']::text[], array['ㅂㅂㅅㅋㅌ','ㅂㅅㅋㅌ','ㅎㅇㅂㅅㅋㅌ']::text[], 'leg', 'quads', 'barbell', 'weight_reps', 'squat', null),
  ('프론트 스쿼트', 'ㅍㄹㅌㅅㅋㅌ', array['프론트','front squat']::text[], array['ㅍㄹㅌ']::text[], 'leg', 'quads', 'barbell', 'weight_reps', 'front-squat', null),
  ('랜드마인 스쿼트', 'ㄹㄷㅁㅇㅅㅋㅌ', array['landmine squat']::text[], '{}'::text[], 'leg', 'quads', 'barbell', 'weight_reps', 'landmine-squat', null),
  ('바벨 런지', 'ㅂㅂㄹㅈ', array['바벨 워킹 런지','바벨 프론트 랙 런지','바벨 백워드 런지']::text[], array['ㅂㅂㅇㅋㄹㅈ','ㅂㅂㅍㄹㅌㄹㄹㅈ','ㅂㅂㅂㅇㄷㄹㅈ']::text[], 'leg', 'quads', 'barbell', 'weight_reps', null, null),
  ('루마니안 데드리프트', 'ㄹㅁㄴㅇㄷㄷㄹㅍㅌ', array['랜드마인 루마니안 데드리프트','RDL','루마니안','스티프 레그 데드리프트','romanian deadlift']::text[], array['ㄹㄷㅁㅇㄹㅁㄴㅇㄷㄷㄹㅍㅌ','ㄹㅁㄴㅇ','ㅅㅌㅍㄹㄱㄷㄷㄹㅍㅌ']::text[], 'leg', 'hamstrings', 'barbell', 'weight_reps', 'romanian-deadlift', null),
  ('굿모닝', 'ㄱㅁㄴ', array['굿모닝 엑서사이즈','good morning']::text[], array['ㄱㅁㄴㅇㅅㅅㅇㅈ']::text[], 'leg', 'hamstrings', 'barbell', 'weight_reps', 'good-morning', null),
  ('힙 쓰러스트', 'ㅎㅆㄹㅅㅌ', array['힙스러스트','바벨 힙 쓰러스트','hip thrust']::text[], array['ㅎㅅㄹㅅㅌ','ㅂㅂㅎㅆㄹㅅㅌ']::text[], 'leg', 'glutes', 'barbell', 'weight_reps', 'hip-thrust', null),
  ('고블릿 스쿼트', 'ㄱㅂㄹㅅㅋㅌ', array['힐 엘리베이티드 고블릿 스쿼트','덤벨 고블릿 스쿼트','케틀벨 고블릿 스쿼트','고블렛 스쿼트','goblet squat']::text[], array['ㅎㅇㄹㅂㅇㅌㄷㄱㅂㄹㅅㅋㅌ','ㄷㅂㄱㅂㄹㅅㅋㅌ','ㅋㅌㅂㄱㅂㄹㅅㅋㅌ','ㄱㅂㄹㅅㅋㅌ']::text[], 'leg', 'quads', 'dumbbell', 'weight_reps', 'goblet-squat', null),
  ('불가리안 스플릿 스쿼트', 'ㅂㄱㄹㅇㅅㅍㄹㅅㅋㅌ', array['스미스 머신 불가리안 스플릿 스쿼트','불스','불가리안','bulgarian split squat']::text[], array['ㅅㅁㅅㅁㅅㅂㄱㄹㅇㅅㅍㄹㅅㅋㅌ','ㅂㅅ','ㅂㄱㄹㅇ']::text[], 'leg', 'quads', 'dumbbell', 'weight_reps', 'bulgarian-split-squat', null),
  ('스플릿 스쿼트', 'ㅅㅍㄹㅅㅋㅌ', array['덤벨 스플릿 스쿼트','split squat']::text[], array['ㄷㅂㅅㅍㄹㅅㅋㅌ']::text[], 'leg', 'quads', 'dumbbell', 'weight_reps', 'split-squat', null),
  ('프론트 풋 엘리베이티드 스플릿 스쿼트', 'ㅍㄹㅌㅍㅇㄹㅂㅇㅌㄷㅅㅍㄹㅅㅋㅌ', array['앞발 올린 스플릿 스쿼트','FFE 스플릿 스쿼트']::text[], array['ㅇㅂㅇㄹㅅㅍㄹㅅㅋㅌ','ffeㅅㅍㄹㅅㅋㅌ']::text[], 'leg', 'quads', 'dumbbell', 'weight_reps', 'front-foot-elevated-split-squat', null),
  ('워킹 런지', 'ㅇㅋㄹㅈ', array['덤벨 런지','덤벨 워킹 런지','walking lunge']::text[], array['ㄷㅂㄹㅈ','ㄷㅂㅇㅋㄹㅈ']::text[], 'leg', 'quads', 'dumbbell', 'weight_reps', 'walking-lunge', null),
  ('런지', 'ㄹㅈ', array['포워드 런지','프론트 런지','맨몸 런지','forward lunge']::text[], array['ㅍㅇㄷㄹㅈ','ㅍㄹㅌㄹㅈ','ㅁㅁㄹㅈ']::text[], 'leg', 'quads', 'bodyweight', 'bodyweight_reps', 'forward-lunge', null),
  ('리버스 런지', 'ㄹㅂㅅㄹㅈ', array['데피싯 리버스 런지','스미스 머신 리버스 런지','백 런지','백워드 런지','덤벨 백 런지','reverse lunge']::text[], array['ㄷㅍㅅㄹㅂㅅㄹㅈ','ㅅㅁㅅㅁㅅㄹㅂㅅㄹㅈ','ㅂㄹㅈ','ㅂㅇㄷㄹㅈ','ㄷㅂㅂㄹㅈ']::text[], 'leg', 'quads', 'dumbbell', 'weight_reps', 'reverse-lunge', null),
  ('레터럴 런지', 'ㄹㅌㄹㄹㅈ', array['사이드 런지','덤벨 사이드 런지','덤벨 레터럴 런지','lateral lunge']::text[], array['ㅅㅇㄷㄹㅈ','ㄷㅂㅅㅇㄷㄹㅈ','ㄷㅂㄹㅌㄹㄹㅈ']::text[], 'leg', 'quads', 'dumbbell', 'weight_reps', 'dumbbell-lateral-lunge', null),
  ('크로스 런지', 'ㅋㄹㅅㄹㅈ', array['커시 런지','덤벨 크로스 런지','커스티 런지','curtsy lunge']::text[], array['ㅋㅅㄹㅈ','ㄷㅂㅋㄹㅅㄹㅈ','ㅋㅅㅌㄹㅈ']::text[], 'leg', 'glutes', 'dumbbell', 'weight_reps', 'dumbbell-curtsy-lunge', null),
  ('스텝업', 'ㅅㅌㅇ', array['덤벨 스텝업','중량 스텝업','step up']::text[], array['ㄷㅂㅅㅌㅇ','ㅈㄹㅅㅌㅇ']::text[], 'leg', 'quads', 'dumbbell', 'weight_reps', 'step-up', null),
  ('덤벨 스모 스쿼트', 'ㄷㅂㅅㅁㅅㅋㅌ', array['스모 스쿼트','와이드 스쿼트','sumo squat']::text[], array['ㅅㅁㅅㅋㅌ','ㅇㅇㄷㅅㅋㅌ']::text[], 'leg', 'glutes', 'dumbbell', 'weight_reps', 'dumbbell-sumo-squat', null),
  ('덤벨 스모 데드리프트', 'ㄷㅂㅅㅁㄷㄷㄹㅍㅌ', array['와이드 데드리프트','dumbbell sumo deadlift']::text[], array['ㅇㅇㄷㄷㄷㄹㅍㅌ']::text[], 'leg', 'glutes', 'dumbbell', 'weight_reps', 'dumbbell-sumo-deadlift', null),
  ('덤벨 루마니안 데드리프트', 'ㄷㅂㄹㅁㄴㅇㄷㄷㄹㅍㅌ', array['덤벨 RDL','덤벨 스티프 레그 데드리프트']::text[], array['ㄷㅂrdl','ㄷㅂㅅㅌㅍㄹㄱㄷㄷㄹㅍㅌ']::text[], 'leg', 'hamstrings', 'dumbbell', 'weight_reps', 'dumbbell-romanian-deadlift', null),
  ('싱글 레그 루마니안 데드리프트', 'ㅅㄱㄹㄱㄹㅁㄴㅇㄷㄷㄹㅍㅌ', array['원레그 데드리프트','싱글 레그 데드리프트','single leg RDL']::text[], array['ㅇㄹㄱㄷㄷㄹㅍㅌ','ㅅㄱㄹㄱㄷㄷㄹㅍㅌ']::text[], 'leg', 'hamstrings', 'dumbbell', 'weight_reps', 'single-leg-romanian-deadlift', null),
  ('덤벨 힙 쓰러스트', 'ㄷㅂㅎㅆㄹㅅㅌ', array['dumbbell hip thrust']::text[], '{}'::text[], 'leg', 'glutes', 'dumbbell', 'weight_reps', 'dumbbell-hip-thrust', null),
  ('케틀벨 스윙', 'ㅋㅌㅂㅅㅇ', array['kettlebell swing']::text[], '{}'::text[], 'leg', 'glutes', 'kettlebell', 'weight_reps', 'kettlebell-swing', null),
  ('레그프레스', 'ㄹㄱㅍㄹㅅ', array['렉프','leg press']::text[], array['ㄹㅍ']::text[], 'leg', 'quads', 'machine', 'weight_reps', 'leg-press', null),
  ('핵 스쿼트', 'ㅎㅅㅋㅌ', array['핵 스쿼트 머신','hack squat']::text[], array['ㅎㅅㅋㅌㅁㅅ']::text[], 'leg', 'quads', 'machine', 'weight_reps', 'hack-squat', null),
  ('벨트 스쿼트', 'ㅂㅌㅅㅋㅌ', array['벨트 스쿼트 머신','belt squat']::text[], array['ㅂㅌㅅㅋㅌㅁㅅ']::text[], 'leg', 'quads', 'machine', 'weight_reps', 'belt-squat', null),
  ('브이 스쿼트', 'ㅂㅇㅅㅋㅌ', array['V 스쿼트','브이 스쿼트 머신','리버스 브이 스쿼트']::text[], array['vㅅㅋㅌ','ㅂㅇㅅㅋㅌㅁㅅ','ㄹㅂㅅㅂㅇㅅㅋㅌ']::text[], 'leg', 'quads', 'machine', 'weight_reps', null, null),
  ('펜듈럼 스쿼트', 'ㅍㄷㄹㅅㅋㅌ', array['펜들럼 스쿼트','펜듈럼 스쿼트 머신']::text[], array['ㅍㄷㄹㅅㅋㅌ','ㅍㄷㄹㅅㅋㅌㅁㅅ']::text[], 'leg', 'quads', 'machine', 'weight_reps', null, null),
  ('레그 익스텐션', 'ㄹㄱㅇㅅㅌㅅ', array['레그익스','익스텐션','leg extension']::text[], array['ㄹㄱㅇㅅ','ㅇㅅㅌㅅ']::text[], 'leg', 'quads', 'machine', 'weight_reps', 'leg-extension', null),
  ('레그 컬', 'ㄹㄱㅋ', array['라잉 레그컬','햄스트링 컬','leg curl']::text[], array['ㄹㅇㄹㄱㅋ','ㅎㅅㅌㄹㅋ']::text[], 'leg', 'hamstrings', 'machine', 'weight_reps', 'leg-curl', null),
  ('시티드 레그컬', 'ㅅㅌㄷㄹㄱㅋ', array['seated leg curl']::text[], '{}'::text[], 'leg', 'hamstrings', 'machine', 'weight_reps', 'seated-leg-curl', null),
  ('스탠딩 햄스트링 컬', 'ㅅㅌㄷㅎㅅㅌㄹㅋ', array['스탠딩 레그컬','스탠딩 햄스트링 컬 머신']::text[], array['ㅅㅌㄷㄹㄱㅋ','ㅅㅌㄷㅎㅅㅌㄹㅋㅁㅅ']::text[], 'leg', 'hamstrings', 'machine', 'weight_reps', null, null),
  ('스미스 머신 스쿼트', 'ㅅㅁㅅㅁㅅㅅㅋㅌ', array['스미스 스쿼트','smith machine squat']::text[], array['ㅅㅁㅅㅅㅋㅌ']::text[], 'leg', 'quads', 'machine', 'weight_reps', 'smith-machine-squat', null),
  ('스미스 머신 힙 쓰러스트', 'ㅅㅁㅅㅁㅅㅎㅆㄹㅅㅌ', array['스미스 힙쓰러스트']::text[], array['ㅅㅁㅅㅎㅆㄹㅅㅌ']::text[], 'leg', 'glutes', 'machine', 'weight_reps', 'smith-machine-hip-thrust', null),
  ('스미스 머신 루마니안 데드리프트', 'ㅅㅁㅅㅁㅅㄹㅁㄴㅇㄷㄷㄹㅍㅌ', array['스미스 RDL']::text[], array['ㅅㅁㅅrdl']::text[], 'leg', 'hamstrings', 'machine', 'weight_reps', 'smith-machine-romanian-deadlift', null),
  ('스미스 머신 스플릿 스쿼트', 'ㅅㅁㅅㅁㅅㅅㅍㄹㅅㅋㅌ', '{}'::text[], '{}'::text[], 'leg', 'quads', 'machine', 'weight_reps', 'smith-machine-split-squat', null),
  ('힙 쓰러스트 머신', 'ㅎㅆㄹㅅㅌㅁㅅ', array['몬스터 글루트 머신']::text[], array['ㅁㅅㅌㄱㄹㅌㅁㅅ']::text[], 'leg', 'glutes', 'machine', 'weight_reps', null, null),
  ('힙 어브덕션 머신', 'ㅎㅇㅂㄷㅅㅁㅅ', array['아웃싸이','아웃타이','힙 어브덕션','hip abduction']::text[], array['ㅇㅇㅆㅇ','ㅇㅇㅌㅇ','ㅎㅇㅂㄷㅅ']::text[], 'leg', 'glutes', 'machine', 'weight_reps', 'hip-abduction-machine', null),
  ('힙 어덕션 머신', 'ㅎㅇㄷㅅㅁㅅ', array['이너싸이','이너타이','힙 애덕션','hip adduction']::text[], array['ㅇㄴㅆㅇ','ㅇㄴㅌㅇ','ㅎㅇㄷㅅ']::text[], 'leg', 'adductors', 'machine', 'weight_reps', 'hip-adduction-machine', null),
  ('글루트 킥백 머신', 'ㄱㄹㅌㅋㅂㅁㅅ', array['힙 익스텐션 머신','리어 킥 머신']::text[], array['ㅎㅇㅅㅌㅅㅁㅅ','ㄹㅇㅋㅁㅅ']::text[], 'leg', 'glutes', 'machine', 'weight_reps', 'machine-glute-kickback', null),
  ('리버스 하이퍼익스텐션', 'ㄹㅂㅅㅎㅇㅍㅇㅅㅌㅅ', array['리버스 하이퍼','reverse hyperextension']::text[], array['ㄹㅂㅅㅎㅇㅍ']::text[], 'leg', 'glutes', 'machine', 'bodyweight_reps', 'reverse-hyperextension', null),
  ('스탠딩 카프 레이즈', 'ㅅㅌㄷㅋㅍㄹㅇㅈ', array['스탠딩 카프 레이즈 머신','카프 레이즈','종아리 운동','standing calf raise']::text[], array['ㅅㅌㄷㅋㅍㄹㅇㅈㅁㅅ','ㅋㅍㄹㅇㅈ','ㅈㅇㄹㅇㄷ']::text[], 'leg', 'calves', 'machine', 'weight_reps', 'standing-calf-raise', null),
  ('시티드 카프 레이즈', 'ㅅㅌㄷㅋㅍㄹㅇㅈ', array['시티드 카프레이즈 머신','시티드 카프','seated calf raise']::text[], array['ㅅㅌㄷㅋㅍㄹㅇㅈㅁㅅ','ㅅㅌㄷㅋㅍ']::text[], 'leg', 'calves', 'machine', 'weight_reps', 'seated-calf-raise', null),
  ('동키 카프 레이즈', 'ㄷㅋㅋㅍㄹㅇㅈ', array['덩키 카프 레이즈','donkey calf raise']::text[], array['ㄷㅋㅋㅍㄹㅇㅈ']::text[], 'leg', 'calves', 'machine', 'weight_reps', 'donkey-calf-raise', null),
  ('레그프레스 카프 레이즈', 'ㄹㄱㅍㄹㅅㅋㅍㄹㅇㅈ', array['시티드 레그 프레스 카프 레이즈','레그프레스 카프','leg press calf raise']::text[], array['ㅅㅌㄷㄹㄱㅍㄹㅅㅋㅍㄹㅇㅈ','ㄹㄱㅍㄹㅅㅋㅍ']::text[], 'leg', 'calves', 'machine', 'weight_reps', 'leg-press-calf-raise', null),
  ('스미스 머신 카프 레이즈', 'ㅅㅁㅅㅁㅅㅋㅍㄹㅇㅈ', array['스미스 카프 레이즈']::text[], array['ㅅㅁㅅㅋㅍㄹㅇㅈ']::text[], 'leg', 'calves', 'machine', 'weight_reps', null, null),
  ('케이블 킥백', 'ㅋㅇㅂㅋㅂ', array['케이블 글루트 킥백','cable kickback']::text[], array['ㅋㅇㅂㄱㄹㅌㅋㅂ']::text[], 'leg', 'glutes', 'cable', 'weight_reps', 'cable-kickback', null),
  ('케이블 풀 스루', 'ㅋㅇㅂㅍㅅㄹ', array['풀스루','cable pull through']::text[], array['ㅍㅅㄹ']::text[], 'leg', 'glutes', 'cable', 'weight_reps', 'cable-pull-through', null),
  ('케이블 힙 어브덕션', 'ㅋㅇㅂㅎㅇㅂㄷㅅ', array['스탠딩 힙 어브덕션','cable hip abduction']::text[], array['ㅅㅌㄷㅎㅇㅂㄷㅅ']::text[], 'leg', 'glutes', 'cable', 'weight_reps', 'cable-standing-hip-abduction', null),
  ('케이블 힙 어덕션', 'ㅋㅇㅂㅎㅇㄷㅅ', array['스탠딩 힙 어덕션','cable hip adduction']::text[], array['ㅅㅌㄷㅎㅇㄷㅅ']::text[], 'leg', 'adductors', 'cable', 'weight_reps', 'cable-standing-hip-adduction', null),
  ('글루트 브릿지', 'ㄱㄹㅌㅂㄹㅈ', array['바벨 글루트 브릿지','덤벨 글루트 브릿지','힙 브릿지','glute bridge']::text[], array['ㅂㅂㄱㄹㅌㅂㄹㅈ','ㄷㅂㄱㄹㅌㅂㄹㅈ','ㅎㅂㄹㅈ']::text[], 'leg', 'glutes', 'bodyweight', 'bodyweight_reps', 'glute-bridge', null),
  ('싱글 레그 글루트 브릿지', 'ㅅㄱㄹㄱㄱㄹㅌㅂㄹㅈ', array['원레그 글루트 브릿지','single leg glute bridge']::text[], array['ㅇㄹㄱㄱㄹㅌㅂㄹㅈ']::text[], 'leg', 'glutes', 'bodyweight', 'bodyweight_reps', 'single-leg-glute-bridge', null),
  ('덩키 킥', 'ㄷㅋㅋ', array['동키 킥','케이블 덩키 킥','donkey kick']::text[], array['ㄷㅋㅋ','ㅋㅇㅂㄷㅋㅋ']::text[], 'leg', 'glutes', 'bodyweight', 'bodyweight_reps', 'donkey-kick', null),
  ('노르딕 햄스트링 컬', 'ㄴㄹㄷㅎㅅㅌㄹㅋ', array['노르딕 컬','nordic curl']::text[], array['ㄴㄹㄷㅋ']::text[], 'leg', 'hamstrings', 'bodyweight', 'bodyweight_reps', 'nordic-hamstring-curl', null),
  ('맨몸 스쿼트', 'ㅁㅁㅅㅋㅌ', array['에어 스쿼트','자중 스쿼트','bodyweight squat']::text[], array['ㅇㅇㅅㅋㅌ','ㅈㅈㅅㅋㅌ']::text[], 'leg', 'quads', 'bodyweight', 'bodyweight_reps', 'bodyweight-squat', null),
  ('점프 스쿼트', 'ㅈㅍㅅㅋㅌ', array['jump squat']::text[], '{}'::text[], 'leg', 'quads', 'bodyweight', 'bodyweight_reps', 'jump-squat', null),
  ('피스톨 스쿼트', 'ㅍㅅㅌㅅㅋㅌ', array['원레그 스쿼트','pistol squat']::text[], array['ㅇㄹㄱㅅㅋㅌ']::text[], 'leg', 'quads', 'bodyweight', 'bodyweight_reps', 'pistol-squat', null),
  ('시시 스쿼트', 'ㅅㅅㅅㅋㅌ', array['씨시 스쿼트','sissy squat']::text[], array['ㅆㅅㅅㅋㅌ']::text[], 'leg', 'quads', 'bodyweight', 'bodyweight_reps', 'sissy-squat', null),
  ('맨몸 카프 레이즈', 'ㅁㅁㅋㅍㄹㅇㅈ', array['카프 레이즈','calf raise']::text[], array['ㅋㅍㄹㅇㅈ']::text[], 'leg', 'calves', 'bodyweight', 'bodyweight_reps', 'calf-raise', null),
  ('시티드 레그 프레스', 'ㅅㅌㄷㄹㄱㅍㄹㅅ', array['수평 레그프레스','seated leg press']::text[], array['ㅅㅍㄹㄱㅍㄹㅅ']::text[], 'leg', 'quads', 'machine', 'weight_reps', null, null),
  ('덤벨 스쿼트', 'ㄷㅂㅅㅋㅌ', array['양손 덤벨 스쿼트','dumbbell squat']::text[], array['ㅇㅅㄷㅂㅅㅋㅌ']::text[], 'leg', 'quads', 'dumbbell', 'weight_reps', null, null),
  ('박스 스쿼트', 'ㅂㅅㅅㅋㅌ', array['box squat']::text[], '{}'::text[], 'leg', 'quads', 'barbell', 'weight_reps', null, null),
  ('글루트 햄 레이즈', 'ㄱㄹㅌㅎㄹㅇㅈ', array['GHR','glute ham raise']::text[], '{}'::text[], 'leg', 'hamstrings', 'bodyweight', 'bodyweight_reps', null, null),
  ('바벨 컬', 'ㅂㅂㅋ', array['컬','이두컬','바벨 바이셉 컬','EZ바 컬','이지바 바이셉 컬','barbell curl']::text[], array['ㅋ','ㅇㄷㅋ','ㅂㅂㅂㅇㅅㅋ','ezㅂㅋ','ㅇㅈㅂㅂㅇㅅㅋ']::text[], 'biceps', null, 'barbell', 'weight_reps', 'ez-bar-curl', null),
  ('리버스 컬', 'ㄹㅂㅅㅋ', array['바벨 리버스 컬','덤벨 리버스 컬','이지바 리버스 컬','reverse curl']::text[], array['ㅂㅂㄹㅂㅅㅋ','ㄷㅂㄹㅂㅅㅋ','ㅇㅈㅂㄹㅂㅅㅋ']::text[], 'biceps', null, 'barbell', 'weight_reps', 'reverse-curl', null),
  ('드래그 컬', 'ㄷㄹㄱㅋ', array['drag curl']::text[], '{}'::text[], 'biceps', null, 'barbell', 'weight_reps', 'drag-curl', null),
  ('덤벨 컬', 'ㄷㅂㅋ', array['덤벨 바이셉 컬','덤벨 이두컬','얼터네이트 덤벨 컬','dumbbell curl']::text[], array['ㄷㅂㅂㅇㅅㅋ','ㄷㅂㅇㄷㅋ','ㅇㅌㄴㅇㅌㄷㅂㅋ']::text[], 'biceps', null, 'dumbbell', 'weight_reps', 'bicep-curl', null),
  ('해머 컬', 'ㅎㅁㅋ', array['해머','덤벨 해머 컬','hammer curl']::text[], array['ㅎㅁ','ㄷㅂㅎㅁㅋ']::text[], 'biceps', null, 'dumbbell', 'weight_reps', 'hammer-curl', null),
  ('인클라인 덤벨 컬', 'ㅇㅋㄹㅇㄷㅂㅋ', array['인클라인 컬','incline dumbbell curl']::text[], array['ㅇㅋㄹㅇㅋ']::text[], 'biceps', null, 'dumbbell', 'weight_reps', 'incline-dumbbell-curl', null),
  ('컨센트레이션 컬', 'ㅋㅅㅌㄹㅇㅅㅋ', array['컨센트레이션','concentration curl']::text[], array['ㅋㅅㅌㄹㅇㅅ']::text[], 'biceps', null, 'dumbbell', 'weight_reps', 'concentration-curl', null),
  ('스파이더 컬', 'ㅅㅍㅇㄷㅋ', array['덤벨 스파이더 컬','이지바 스파이더 컬','spider curl']::text[], array['ㄷㅂㅅㅍㅇㄷㅋ','ㅇㅈㅂㅅㅍㅇㄷㅋ']::text[], 'biceps', null, 'dumbbell', 'weight_reps', 'spider-curl', null),
  ('프리처 컬', 'ㅍㄹㅊㅋ', array['프리쳐 컬','스캇 컬','이지바 프리쳐 컬','바벨 프리처 컬','preacher curl']::text[], array['ㅍㄹㅊㅋ','ㅅㅋㅋ','ㅇㅈㅂㅍㄹㅊㅋ','ㅂㅂㅍㄹㅊㅋ']::text[], 'biceps', null, 'barbell', 'weight_reps', 'preacher-curl', null),
  ('바이셉 컬 머신', 'ㅂㅇㅅㅋㅁㅅ', array['암 컬 머신','이두 컬 머신','바이셉스 컬 머신']::text[], array['ㅇㅋㅁㅅ','ㅇㄷㅋㅁㅅ','ㅂㅇㅅㅅㅋㅁㅅ']::text[], 'biceps', null, 'machine', 'weight_reps', null, null),
  ('케이블 컬', 'ㅋㅇㅂㅋ', array['케이블 바이셉 컬','케이블 바이셉스 컬','cable curl']::text[], array['ㅋㅇㅂㅂㅇㅅㅋ','ㅋㅇㅂㅂㅇㅅㅅㅋ']::text[], 'biceps', null, 'cable', 'weight_reps', 'cable-curl', null),
  ('로프 해머 컬', 'ㄹㅍㅎㅁㅋ', array['케이블 해머컬','케이블 로프 해머 컬','rope hammer curl']::text[], array['ㅋㅇㅂㅎㅁㅋ','ㅋㅇㅂㄹㅍㅎㅁㅋ']::text[], 'biceps', null, 'cable', 'weight_reps', 'rope-hammer-curl', null),
  ('덤벨 프리처 컬', 'ㄷㅂㅍㄹㅊㅋ', array['덤벨 프리쳐 컬','원암 프리처 컬','dumbbell preacher curl']::text[], array['ㄷㅂㅍㄹㅊㅋ','ㅇㅇㅍㄹㅊㅋ']::text[], 'biceps', null, 'dumbbell', 'weight_reps', null, null),
  ('라잉 트라이셉스 익스텐션', 'ㄹㅇㅌㄹㅇㅅㅅㅇㅅㅌㅅ', array['원암 덤벨 스컬크러셔','덤벨 스컬크러셔','스컬크러셔','라잉 바벨 트라이셉 익스텐션','프렌치프레스','skull crusher']::text[], array['ㅇㅇㄷㅂㅅㅋㅋㄹㅅ','ㄷㅂㅅㅋㅋㄹㅅ','ㅅㅋㅋㄹㅅ','ㄹㅇㅂㅂㅌㄹㅇㅅㅇㅅㅌㅅ','ㅍㄹㅊㅍㄹㅅ']::text[], 'triceps', 'general', 'barbell', 'weight_reps', 'skull-crusher', null),
  ('클로즈그립 벤치프레스', 'ㅋㄹㅈㄱㄹㅂㅊㅍㄹㅅ', array['클그벤','내로우 그립 벤치','클로즈 그립 벤치','close grip bench press']::text[], array['ㅋㄱㅂ','ㄴㄹㅇㄱㄹㅂㅊ','ㅋㄹㅈㄱㄹㅂㅊ']::text[], 'triceps', 'general', 'barbell', 'weight_reps', 'close-grip-bench-press', null),
  ('오버헤드 트라이셉스 익스텐션', 'ㅇㅂㅎㄷㅌㄹㅇㅅㅅㅇㅅㅌㅅ', array['오버헤드 덤벨 트라이셉스 익스텐션','덤벨 트라이셉 익스텐션','프렌치 프레스','overhead triceps extension']::text[], array['ㅇㅂㅎㄷㄷㅂㅌㄹㅇㅅㅅㅇㅅㅌㅅ','ㄷㅂㅌㄹㅇㅅㅇㅅㅌㅅ','ㅍㄹㅊㅍㄹㅅ']::text[], 'triceps', 'long_head', 'dumbbell', 'weight_reps', 'dumbbell-overhead-tricep-extension', null),
  ('원암 오버헤드 트라이셉스 익스텐션', 'ㅇㅇㅇㅂㅎㄷㅌㄹㅇㅅㅅㅇㅅㅌㅅ', array['원암 덤벨 트라이셉 익스텐션','싱글 암 오버헤드 익스텐션']::text[], array['ㅇㅇㄷㅂㅌㄹㅇㅅㅇㅅㅌㅅ','ㅅㄱㅇㅇㅂㅎㄷㅇㅅㅌㅅ']::text[], 'triceps', 'long_head', 'dumbbell', 'weight_reps', 'single-arm-dumbbell-tricep-extension', null),
  ('킥백', 'ㅋㅂ', array['덤벨 킥백','원 암 덤벨 킥백','트라이셉스 킥백','triceps kickback']::text[], array['ㄷㅂㅋㅂ','ㅇㅇㄷㅂㅋㅂ','ㅌㄹㅇㅅㅅㅋㅂ']::text[], 'triceps', 'general', 'dumbbell', 'weight_reps', 'tricep-kickback', null),
  ('케이블 푸시다운', 'ㅋㅇㅂㅍㅅㄷㅇ', array['원암 케이블 푸시다운','로프 푸시다운','푸시다운','프레스다운','트라이셉스 푸시다운','pushdown']::text[], array['ㅇㅇㅋㅇㅂㅍㅅㄷㅇ','ㄹㅍㅍㅅㄷㅇ','ㅍㅅㄷㅇ','ㅍㄹㅅㄷㅇ','ㅌㄹㅇㅅㅅㅍㅅㄷㅇ']::text[], 'triceps', 'general', 'cable', 'weight_reps', 'tricep-pushdown', null),
  ('케이블 오버헤드 트라이셉스 익스텐션', 'ㅋㅇㅂㅇㅂㅎㄷㅌㄹㅇㅅㅅㅇㅅㅌㅅ', array['오버헤드 케이블 트라이셉 익스텐션','케이블 오버헤드 익스텐션']::text[], array['ㅇㅂㅎㄷㅋㅇㅂㅌㄹㅇㅅㅇㅅㅌㅅ','ㅋㅇㅂㅇㅂㅎㄷㅇㅅㅌㅅ']::text[], 'triceps', 'long_head', 'cable', 'weight_reps', 'overhead-tricep-extension', null),
  ('트라이셉스 익스텐션 머신', 'ㅌㄹㅇㅅㅅㅇㅅㅌㅅㅁㅅ', array['트라이셉 익스텐션 머신','오버헤드 트라이셉 익스텐션 머신','삼두 머신']::text[], array['ㅌㄹㅇㅅㅇㅅㅌㅅㅁㅅ','ㅇㅂㅎㄷㅌㄹㅇㅅㅇㅅㅌㅅㅁㅅ','ㅅㄷㅁㅅ']::text[], 'triceps', 'general', 'machine', 'weight_reps', null, null),
  ('트라이셉스 딥스', 'ㅌㄹㅇㅅㅅㄷㅅ', array['삼두 딥스','평행봉 딥스','triceps dip']::text[], array['ㅅㄷㄷㅅ','ㅍㅎㅂㄷㅅ']::text[], 'triceps', 'general', 'bodyweight', 'bodyweight_reps', 'dip', null),
  ('벤치 딥스', 'ㅂㅊㄷㅅ', array['벤치딥','bench dip']::text[], array['ㅂㅊㄷ']::text[], 'triceps', 'general', 'bodyweight', 'bodyweight_reps', 'bench-dip', null),
  ('어시스트 딥스 머신', 'ㅇㅅㅅㅌㄷㅅㅁㅅ', array['어시스트 딥스','보조 딥스','그래비트론','assisted dip']::text[], array['ㅇㅅㅅㅌㄷㅅ','ㅂㅈㄷㅅ','ㄱㄹㅂㅌㄹ']::text[], 'triceps', 'general', 'machine', 'assist_reps', 'assisted-dip', null),
  ('시티드 딥스 머신', 'ㅅㅌㄷㄷㅅㅁㅅ', array['딥스 머신','트라이셉 딥 머신']::text[], array['ㄷㅅㅁㅅ','ㅌㄹㅇㅅㄷㅁㅅ']::text[], 'triceps', 'general', 'machine', 'weight_reps', null, null),
  ('다이아몬드 푸시업', 'ㄷㅇㅇㅁㄷㅍㅅㅇ', array['다이아몬드 푸쉬업','클로즈그립 푸시업','diamond push up']::text[], array['ㄷㅇㅇㅁㄷㅍㅅㅇ','ㅋㄹㅈㄱㄹㅍㅅㅇ']::text[], 'triceps', 'general', 'bodyweight', 'bodyweight_reps', 'diamond-push-up', null),
  ('JM 프레스', 'jmㅍㄹㅅ', array['제이엠 프레스','jm press']::text[], array['ㅈㅇㅇㅍㄹㅅ']::text[], 'triceps', 'general', 'barbell', 'weight_reps', null, null),
  ('크런치', 'ㅋㄹㅊ', array['복근 크런치','crunch']::text[], array['ㅂㄱㅋㄹㅊ']::text[], 'core', 'rectus_abdominis', 'bodyweight', 'bodyweight_reps', 'crunch', null),
  ('리버스 크런치', 'ㄹㅂㅅㅋㄹㅊ', array['역크런치','reverse crunch']::text[], array['ㅇㅋㄹㅊ']::text[], 'core', 'rectus_abdominis', 'bodyweight', 'bodyweight_reps', 'reverse-crunch', null),
  ('싯업', 'ㅅㅇ', array['윗몸일으키기','씻업','sit up']::text[], array['ㅇㅁㅇㅇㅋㄱ','ㅆㅇ']::text[], 'core', 'rectus_abdominis', 'bodyweight', 'bodyweight_reps', null, null),
  ('디클라인 싯업', 'ㄷㅋㄹㅇㅅㅇ', array['디클라인 윗몸일으키기','decline sit up']::text[], array['ㄷㅋㄹㅇㅇㅁㅇㅇㅋㄱ']::text[], 'core', 'rectus_abdominis', 'bodyweight', 'bodyweight_reps', 'decline-sit-up', null),
  ('웨이티드 크런치', 'ㅇㅇㅌㄷㅋㄹㅊ', array['중량 크런치','원판 크런치','weighted crunch','크런치 무게','크런치 중량']::text[], array['ㅈㄹㅋㄹㅊ','ㅇㅍㅋㄹㅊ','ㅋㄹㅊㅁㄱ','ㅋㄹㅊㅈㄹ']::text[], 'core', 'rectus_abdominis', 'other', 'weight_reps', 'weighted-crunch', null),
  ('케이블 크런치', 'ㅋㅇㅂㅋㄹㅊ', array['니링 케이블 크런치','케이블 복근','cable crunch']::text[], array['ㄴㄹㅋㅇㅂㅋㄹㅊ','ㅋㅇㅂㅂㄱ']::text[], 'core', 'rectus_abdominis', 'cable', 'weight_reps', 'cable-crunch', null),
  ('복근 크런치 머신', 'ㅂㄱㅋㄹㅊㅁㅅ', array['크런치 머신','앱 크런치 머신','라잉 크런치 머신','애브 크런치']::text[], array['ㅋㄹㅊㅁㅅ','ㅇㅋㄹㅊㅁㅅ','ㄹㅇㅋㄹㅊㅁㅅ','ㅇㅂㅋㄹㅊ']::text[], 'core', 'rectus_abdominis', 'machine', 'weight_reps', null, null),
  ('행잉 레그레이즈', 'ㅎㅇㄹㄱㄹㅇㅈ', array['레그레이즈','다리 들어올리기','hanging leg raise']::text[], array['ㄹㄱㄹㅇㅈ','ㄷㄹㄷㅇㅇㄹㄱ']::text[], 'core', 'rectus_abdominis', 'bodyweight', 'bodyweight_reps', 'hanging-leg-raise', null),
  ('행잉 니 레이즈', 'ㅎㅇㄴㄹㅇㅈ', array['니레이즈','행잉 니업','hanging knee raise']::text[], array['ㄴㄹㅇㅈ','ㅎㅇㄴㅇ']::text[], 'core', 'rectus_abdominis', 'bodyweight', 'bodyweight_reps', 'hanging-knee-raise', null),
  ('라잉 레그레이즈', 'ㄹㅇㄹㄱㄹㅇㅈ', array['레그 레이즈','누워서 레그레이즈','lying leg raise']::text[], array['ㄹㄱㄹㅇㅈ','ㄴㅇㅅㄹㄱㄹㅇㅈ']::text[], 'core', 'rectus_abdominis', 'bodyweight', 'bodyweight_reps', 'lying-leg-raise', null),
  ('브이업', 'ㅂㅇㅇ', array['V업','v up']::text[], array['vㅇ']::text[], 'core', 'rectus_abdominis', 'bodyweight', 'bodyweight_reps', 'v-up', null),
  ('시티드 니업', 'ㅅㅌㄷㄴㅇ', array['시티드 니 턱','니업','seated knee tuck']::text[], array['ㅅㅌㄷㄴㅌ','ㄴㅇ']::text[], 'core', 'rectus_abdominis', 'bodyweight', 'bodyweight_reps', 'seated-knee-tuck', null),
  ('할로우 락', 'ㅎㄹㅇㄹ', array['할로우 바디 락','hollow rock']::text[], array['ㅎㄹㅇㅂㄷㄹ']::text[], 'core', 'rectus_abdominis', 'bodyweight', 'bodyweight_reps', 'hollow-rock', null),
  ('토터치 크런치', 'ㅌㅌㅊㅋㄹㅊ', array['토 터치','발끝 터치 크런치','toe touch']::text[], array['ㅌㅌㅊ','ㅂㄲㅌㅊㅋㄹㅊ']::text[], 'core', 'rectus_abdominis', 'bodyweight', 'bodyweight_reps', 'toe-touch', null),
  ('앱 롤아웃', 'ㅇㄹㅇㅇ', array['복근 롤아웃','아브 롤아웃','롤아웃','복근롤러','애브 휠','ab wheel rollout']::text[], array['ㅂㄱㄹㅇㅇ','ㅇㅂㄹㅇㅇ','ㄹㅇㅇ','ㅂㄱㄹㄹ','ㅇㅂㅎ']::text[], 'core', 'rectus_abdominis', 'other', 'bodyweight_reps', 'ab-wheel', null),
  ('러시안 트위스트', 'ㄹㅅㅇㅌㅇㅅㅌ', array['웨이티드 러시안 트위스트','트위스트','russian twist']::text[], array['ㅇㅇㅌㄷㄹㅅㅇㅌㅇㅅㅌ','ㅌㅇㅅㅌ']::text[], 'core', 'obliques', 'bodyweight', 'bodyweight_reps', 'russian-twist', null),
  ('바이시클 크런치', 'ㅂㅇㅅㅋㅋㄹㅊ', array['자전거 크런치','복근 에어 바이크','bicycle crunch']::text[], array['ㅈㅈㄱㅋㄹㅊ','ㅂㄱㅇㅇㅂㅇㅋ']::text[], 'core', 'obliques', 'bodyweight', 'bodyweight_reps', 'bicycle-crunch', null),
  ('힐 터치', 'ㅎㅌㅊ', array['힐 터치 크런치','힐 탭','사이드 크런치','heel tap']::text[], array['ㅎㅌㅊㅋㄹㅊ','ㅎㅌ','ㅅㅇㄷㅋㄹㅊ']::text[], 'core', 'obliques', 'bodyweight', 'bodyweight_reps', 'heel-tap', null),
  ('팔로프 프레스', 'ㅍㄹㅍㅍㄹㅅ', array['케이블 팔로프 프레스','pallof press']::text[], array['ㅋㅇㅂㅍㄹㅍㅍㄹㅅ']::text[], 'core', 'obliques', 'cable', 'weight_reps', 'pallof-press', null),
  ('캡틴체어 레그 레이즈', 'ㅋㅌㅊㅇㄹㄱㄹㅇㅈ', array['캡틴체어 니 레이즈','캡틴스 체어 레그 레이즈','버티컬 레그 레이즈']::text[], array['ㅋㅌㅊㅇㄴㄹㅇㅈ','ㅋㅌㅅㅊㅇㄹㄱㄹㅇㅈ','ㅂㅌㅋㄹㄱㄹㅇㅈ']::text[], 'core', 'rectus_abdominis', 'machine', 'bodyweight_reps', null, null)
on conflict (coalesce(owner_id::text,'global'), name) do update set
  chosung       = excluded.chosung,
  aliases       = excluded.aliases,
  alias_chosung = excluded.alias_chosung,
  muscle_group  = excluded.muscle_group,
  sub_region    = excluded.sub_region,
  equipment     = excluded.equipment,
  tracking_type = excluded.tracking_type,
  asset_slug    = excluded.asset_slug;

-- ── 3. 안 쓰이는 공용 종목 20개 삭제 ──
-- not exists 로 기록이 걸린 것은 남긴다. 남는 게 있으면 아래 확인 쿼리에 잡힌다.
delete from exercises e
where e.owner_id is null
  and e.name in ('클랩 푸시업', '메도우즈 로우', '클로즈그립 랫풀다운', '언더그립 랫풀다운', '랜드마인 루마니안 데드리프트', '바벨 글루트 브릿지', '힐 엘리베이티드 고블릿 스쿼트', '데피싯 리버스 런지', '덤벨 글루트 브릿지', '스미스 머신 불가리안 스플릿 스쿼트', '스미스 머신 리버스 런지', '덤벨 스컬크러셔', '원암 덤벨 스컬크러셔', '로프 푸시다운', '원암 케이블 푸시다운', '캡틴체어 니 레이즈', '웨이티드 러시안 트위스트', '덤벨 사이드 벤드', '케이블 우드찹', '토르소 로테이션 머신')
  and not exists (select 1 from workout_entries w where w.exercise_id = e.id);

-- ── 4. 사용자가 실수로 만든 커스텀 종목 정리 ──
-- 'ㄱㅇㅂ' 는 오타다. 기록에 쓰였으면 지우지 않는다.
delete from exercises e
where e.owner_id is not null
  and e.name = 'ㄱㅇㅂ'
  and not exists (select 1 from workout_entries w where w.exercise_id = e.id);
